site_name: Red Hat Marketplace
nav:
  - Introduction: index.md
  - Getting Started:
    - Pre-work: about.md
  ##TEST SECTION
  - Marketplace Workshop:
    - Lecture 1: lecture/lecture1.pdf
    - Lab 1: lab1.md
    - Lectue 2: lecture/lecture2.pdf
    - Lab 2: lab2.md
  - Resources:
    - Resource 1: externallink.html
    - Resource 2: externallink.html
theme: 
  name: material
  logo: 'images/redhat.png'
  palette:
    primary: black
    accent: red
    